apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: mt4zdr7pk-go 
  janus-idp.io/tekton: mt4zdr7pk-go
  backstage.io/kubernetes-id: mt4zdr7pk-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mt4zdr7pk-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml