apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mt4zdr7pk-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mt4zdr7pk-go 
  name: mt4zdr7pk-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mt4zdr7pk-go 
